[tool.poetry]
name = "exasol-bucketfs-utils-python"
version = "0.1.0"
description = "BucketFS utilities for the Python programming language"

license = "MIT"

authors = [
    "Torsten Kilias <torsten.kilias@exasol.com>",
    "Anastasiia Sergienko <anastasiia.sergienko@exasol.com>"
]

readme = 'README.rst'

repository = "https://github.com/exasol/bucketfs-utils-python"
homepage = "https://github.com/exasol/bucketfs-utils-python"

keywords = ['exasol', 'bucketfs']

[tool.poetry.dependencies]
python = ">=3.6.1,<4.0"
requests = ">=2.24.0"
joblib=">=1.0.1"
typeguard = ">=2.11.1"


[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
pytest-cov = "^2.10.1"
Sphinx = "^3.5.3"
poethepoet = "^0.10.0"
myst-parser = "^0.14.0"
pyexasol = "^0.17.0"
dill = "^0.3.4"
exasol-udf-mock-python = { git = "https://github.com/exasol/udf-mock-python.git", branch = "master" }

[tool.poe.tasks]
build-html-doc = {shell = """
    cd "$(git rev-parse --show-toplevel)/doc";
    make clean-build; make html
    """ }
open-html-doc = { shell = """
    cd "$(git rev-parse --show-toplevel)/doc";
    xdg-open _build/html/index.html""" }
build-and-open-html-doc = [ "build-html-doc", "open-html-doc" ]

commit-html-doc-to-github-pages-main = { shell = "cd $(git rev-parse --show-toplevel)/doc; bash deploy-to-github-pages-main.sh commit" }
push-html-doc-to-github-pages-main = { shell = "cd $(git rev-parse --show-toplevel)/doc; bash deploy-to-github-pages-main.sh push" }
commit-html-doc-to-github-pages-current = { shell = "cd $(git rev-parse --show-toplevel)/doc; bash deploy-to-github-pages-current.sh commit" }
push-html-doc-to-github-pages-current = { shell = "cd $(git rev-parse --show-toplevel)/doc; bash deploy-to-github-pages-current.sh push" }

test =  "pytest tests"
