[tool.poetry]
name = "exasol-bucketfs-utils-python"
version = "0.1.0"
description = "BucketFS utilities for the Python programming language"

license = "MIT"

authors = [
    "Torsten Kilias <torsten.kilias@exasol.com>",
    "Anastasiia Sergienko <anastasiia.sergienko@exasol.com>"
]

readme = 'README.md'

repository = "https://github.com/exasol/bucketfs-utils-python"
homepage = "https://github.com/exasol/bucketfs-utils-python"

keywords = ['exasol', 'bucketfs']

[tool.poetry.dependencies]
python = ">=3.6.1"
requests = "^2.24.0"
joblib="^1.0.1"
typeguard = "^2.11.1"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
pytest-cov = "^2.10.1"
