name: Build and check documentation for current branch

on:
  push:
    branches-ignore:
      - main
      - github-pages/*

jobs:
  create_github_pages_docs:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.4
    - name: Poetry install
      run: poetry install
    - name: Test deploy documentation to github-pages-main branch
      run: |
        git version
        git fetch
        git branch -v
        poetry run poe commit-html-doc-to-github-pages-current
